from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from io import BytesIO

def generate_pdf(data, mode="invoice", output_path=None):
    """
    Generate an invoice PDF from a data dictionary.

    Expected 'data' structure:
    {
        "business_name": "LAC Invoice Generator",
        "client_name": "Demo Client",
        "reference": "INV-001",
        "items": [
            {"description": "Website Design", "quantity": 1, "unit_price": 15000, "total": 15000},
            ...
        ]
    }
    """
    buffer = output_path or BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    y = height - 50

    # ---- Header ----
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, f"{data.get('business_name', 'Invoice')}")
    y -= 25
    c.setFont("Helvetica", 12)
    c.drawString(50, y, f"Client: {data.get('client_name', 'Demo Client')}")
    y -= 18
    c.drawString(50, y, f"Reference No: {data.get('reference', 'INV-001')}")
    y -= 30

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Invoice Details")
    y -= 20

    # ---- Table Headers ----
    c.setFont("Helvetica-Bold", 10)
    c.drawString(50, y, "Description")
    c.drawString(250, y, "Qty")
    c.drawString(320, y, "Unit Price")
    c.drawString(420, y, "Total")
    y -= 15
    c.line(45, y, 550, y)
    y -= 10

    subtotal = 0
    items = data.get("items", [])

    # ---- Item Rows ----
    if not items:
        c.setFont("Helvetica", 10)
        c.drawString(50, y, "No items available.")
        y -= 20
    else:
        for item in items:
            desc = str(item.get("description", "")).strip()
            qty = float(item.get("quantity", 1))
            unit_price = float(item.get("unit_price", 0))
            total = float(item.get("total", qty * unit_price))
            subtotal += total

            c.setFont("Helvetica", 10)
            c.drawString(50, y, desc[:40])
            c.drawString(250, y, str(qty))
            c.drawString(320, y, f"R{unit_price:,.2f}")
            c.drawString(420, y, f"R{total:,.2f}")
            y -= 18

            if y < 100:  # pagination
                c.showPage()
                y = height - 50

    # ---- Totals ----
    vat = subtotal * 0.15
    total_due = subtotal + vat

    y -= 15
    c.line(45, y, 550, y)
    y -= 20

    c.setFont("Helvetica-Bold", 10)
    c.drawString(320, y, "Subtotal:")
    c.drawRightString(550, y, f"R{subtotal:,.2f}")
    y -= 15
    c.drawString(320, y, "VAT (15%):")
    c.drawRightString(550, y, f"R{vat:,.2f}")
    y -= 15
    c.drawString(320, y, "Total Due:")
    c.drawRightString(550, y, f"R{total_due:,.2f}")

    # ---- Footer ----
    y -= 40
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, y, "Thank you for your business.")
    c.drawRightString(550, y, "Generated by LAC Accounting Automations")

    c.showPage()
    c.save()

    if not output_path:
        pdf = buffer.getvalue()
        buffer.close()
        return pdf